# Copyright (c) 2018 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language: java
jdk:
  - oraclejdk8

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty

    - os: osx
      osx_image: xcode9.3


before_install:
  - source .CI/travis/install-arrayfire.sh
  - source .CI/travis/install-khiva.sh
install:
  - source .CI/travis/install.sh
script:
  - jdk_switcher use openjdk8
  - source .CI/travis/build_and_test.sh
