# Copyright (c) 2019 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language: java

matrix:
  include:
    - os: linux
      dist: bionic
      jdk: openjdk8
      env:
        - LD_LIBRARY_PATH=/opt/khiva/lib
        - PATH=/opt/python/3.7.6/bin:$PATH
      cache:
       directories:
         - ${TRAVIS_BUILD_DIR}/installers
         - ${HOME}/.m2
         - ${HOME}/.conan
         - ${TRAVIS_BUILD_DIR}/cmake
      before_install:
        - pip install --upgrade pip
        - pip install conan==1.24.0
      install:
        - source .CI/travis/install-arrayfire.sh
        - source .CI/travis/install-khiva.sh
      script:
        - source .CI/travis/build-and-test.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF Linux  -cf ./target/site/jacoco/jacoco.xml

    - os: osx
      osx_image: xcode9.3
      jdk: oraclejdk8
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/installers
          - ${HOME}/.m2
          - ${HOME}/.conan
          - ${TRAVIS_BUILD_DIR}/cmake
          - ${HOME}/Library/Caches/Homebrew
          - ${HOME}/.pyenv
      env:
        - TRAVIS_PYTHON_VERSION=3.7.6
        - PATH=$HOME/.pyenv/shims:$HOME/.pyenv/versions/${TRAVIS_PYTHON_VERSION}/bin:$PATH
        - PYTHON_VERSION=$(echo $TRAVIS_PYTHON_VERSION | awk -F'.' '{print $1 "." $2}')
        - DYLD_FALLBACK_LIBRARY_PATH=/usr/local/lib
      before_install:
        - brew upgrade pyenv
        - pyenv install -l
        - pyenv install ${TRAVIS_PYTHON_VERSION}
        - pyenv init -
        - pyenv local ${TRAVIS_PYTHON_VERSION}
        - pip${PYTHON_VERSION} install --upgrade pip
        - pip${PYTHON_VERSION} install conan
      install:
        - source .CI/travis/install-arrayfire.sh
        - source .CI/travis/install-khiva.sh
      script:
        - source .CI/travis/build-and-test.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF MacOS

    - os: osx
      osx_image: xcode9.3
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/installers
          - ${HOME}/.m2
          - ${HOME}/.conan
          - ${TRAVIS_BUILD_DIR}/cmake
          - ${HOME}/Library/Caches/Homebrew
          - ${HOME}/.pyenv
      env:
        - JDK='Oracle JDK 9'
        - TRAVIS_PYTHON_VERSION=3.7.6
        - PATH=$HOME/.pyenv/shims:$HOME/.pyenv/versions/${TRAVIS_PYTHON_VERSION}/bin:$PATH
        - PYTHON_VERSION=$(echo $TRAVIS_PYTHON_VERSION | awk -F'.' '{print $1 "." $2}')
        - DYLD_FALLBACK_LIBRARY_PATH=/usr/local/lib
      before_install:
        - brew upgrade pyenv
        - pyenv install -l
        - pyenv install ${TRAVIS_PYTHON_VERSION}
        - pyenv init -
        - pyenv local ${TRAVIS_PYTHON_VERSION}
        - pip${PYTHON_VERSION} install --upgrade pip
        - pip${PYTHON_VERSION} install conan
      install:
        - source .CI/travis/install-arrayfire.sh
        - source .CI/travis/install-khiva.sh
        - brew update
        - brew tap homebrew/cask-cask
        - brew tap caskroom/versions
        - brew cask info java
        - brew cask install java
      script:
        - source .CI/travis/build-and-test.sh
