# Copyright (c) 2019 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language: java

matrix:
  include:
    - os: linux
      dist: bionic
      jdk: openjdk8
      python: "3.6"
      cache:
       directories:
         - ${TRAVIS_BUILD_DIR}/installers
         - ${HOME}/.m2
         - ${HOME}/.conan
         - ${TRAVIS_BUILD_DIR}/cmake
      install:
        - source .CI/travis/install-arrayfire.sh
        - source .CI/travis/install-khiva.sh
      script:
        - source .CI/travis/build-and-test.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF Linux  -cf ./target/site/jacoco/jacoco.xml

    - os: osx
      osx_image: xcode9.3
      jdk: oraclejdk8
      env:
        - TRAVIS_PYTHON_VERSION=3.6.5
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/installers
          - ${HOME}/.m2
          - ${HOME}/.conan
          - ${TRAVIS_BUILD_DIR}/cmake
          - ${HOME}/Library/Caches/Homebrew
          - ${HOME}/.pyenv
      install:
        - source .CI/travis/install-arrayfire.sh
        - source .CI/travis/install-khiva.sh
      script:
        - source .CI/travis/build-and-test.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF MacOS

    - os: osx
      osx_image: xcode9.3
      env:
        - JDK='Oracle JDK 9'
        - TRAVIS_PYTHON_VERSION=3.6.5
      cache:
       directories:
         - ${TRAVIS_BUILD_DIR}/installers
         - ${HOME}/.m2
         - ${HOME}/.conan
         - ${TRAVIS_BUILD_DIR}/cmake
         - ${HOME}/Library/Caches/Homebrew
         - ${HOME}/.pyenv
      install:
        - source .CI/travis/install-arrayfire.sh
        - source .CI/travis/install-khiva.sh
        - brew update
        - brew tap caskroom/cask
        - brew tap caskroom/versions
        - brew cask info java
        - brew cask install java
      script:
        - source .CI/travis/build-and-test.sh
